# Default values for sample-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.wdf.sap.corp:51032/sandbox/public-sample-repo:latest
  pullPolicy: IfNotPresent
service:
  name: sample-service
  type: ClusterIP
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

