# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.wdf.sap.corp:51032/sandbox/public-sample-repo:latest
  pullPolicy: IfNotPresent
service:
  name: sample-service
  type: NodePort
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

