applicationId: infrastructure-sample-service
applicationPort: 8080
image:
  repository: docker.wdf.sap.corp:51032/sandbox/public-sample-repo:1.0.0-SNAPSHOT-fadb26a
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

